version: '2.2'

networks:
  pcp-bridge-network:
    external: true

services:
  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.2
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.2"
    restart: always

  rosboard:
    image: aictrobotics/rosboard:latest
    container_name: rosboard
    depends_on:
      - ros-master
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.5
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.5"
    ports:
      - "172.30.1.19:8888:8888"
    command: >
      bash -c "source ~/catkin_ws/devel/setup.bash && rosrun rosboard rosboard_node"
    # command: >  
    #   bash -c "tail -F anything"
    privileged: true
    restart: always
