version: '2.2'

networks:
  pcp-bridge-network:
    external: true

services:
  ros-master:
    image: ros:melodic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.2
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.2"
    restart: always

  joy-driver:
    image: aictrobotics/mobile-manipulator:latest
    container_name: joy-driver
    depends_on:
      - ros-master
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.3
    command: >
      bash -c "source ~/catkin_ws/devel/setup.bash && roslaunch joy dual_joy.launch"
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.3"
    privileged: true
    restart: always

  joy-to-mm:
    image: aictrobotics/mobile-manipulator:latest
    container_name: joy-to-mm
    depends_on:
      - ros-master
      - joy-driver
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.4
    command: >
      bash -c "source ~/catkin_ws/devel/setup.bash && rosrun joy_to_mm joy_to_mm_node.py"
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.4"
    privileged: true
    restart: always


  manipulator-simulator:
    image: aictrobotics/mobile-manipulator:latest
    container_name: manipulator-simulator
    depends_on:
      - ros-master
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.5
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.5"
      - "DISPLAY=unix$DISPLAY"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "source ~/catkin_ws/devel/setup.bash && roslaunch ur_gazebo ur3e_pos_bringup.launch"
    privileged: true
    restart: always

  # mobile-base-simulator:
  #   image: aictrobotics/mobile-manipulator:latest
  #   container_name: mobile-base-simulator
  #   depends_on:
  #     - ros-master
  #   networks:
  #     pcp-bridge-network:
  #       ipv4_address: 192.168.56.6
  #   environment:
  #     - "ROS_MASTER_URI=http://192.168.56.2:11311"
  #     - "ROS_HOSTNAME=192.168.56.6"
  #     - "DISPLAY=unix$DISPLAY"
  #   volumes: 
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #   command: >
  #     bash -c "source ~/catkin_ws/devel/setup.bash && roslaunch mir_gazebo mir_maze_world.launch"
  #   privileged: true
  #   restart: always

  dev-container:
    image: aictrobotics/mobile-manipulator:latest
    container_name: dev-container
    depends_on:
      - ros-master
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.7
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.7"
      - "DISPLAY=unix$DISPLAY"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/aict/github/pcp/mobile-manipulator:/root/catkin_ws/src/mobile-manipulator
      - /home/aict/github/universal_robot:/root/catkin_ws/src/fmauch_universal_robot
    command: >
      bash -c "tail -F anything"
    privileged: true
    restart: always