version: '2.2'

networks:
  pcp-macvlan-network:
    name: pcp-macvlan-network
    driver: macvlan
    driver_opts:
      parent: enp89s0
    ipam:
      config:
        - subnet: "192.168.12.0/24"
          # ip_range: "192.168.0.64/26"
          gateway: "192.168.12.1"

services:
  ros-master:
    image: ros:melodic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    networks:
      pcp-macvlan-network:
        ipv4_address: 192.168.12.2
    environment:
      - "ROS_MASTER_URI=http://192.168.12.2:11311"
      - "ROS_HOSTNAME=192.168.12.2"
    # ports:
    #   - "192.168.12.250:11311:11311"      
    privileged: true
    restart: always

  rosbridge-suite:
    image: aictrobotics/rosbridge-suite:latest
    container_name: rosbridge-suite
    command: >
      bash -c "roslaunch rosbridge_server rosbridge_websocket.launch"
    networks:
      pcp-macvlan-network:
        ipv4_address: 192.168.12.3
    # ports:
    #   - "9090:9090"
    environment:
      - "ROS_MASTER_URI=http://192.168.12.2:11311"
      - "ROS_HOSTNAME=192.168.12.3"
    privileged: true      
    restart: always

  foxglove-studio:
    image: ghcr.io/foxglove/studio:latest
    container_name: foxglove-studio
    networks:
      pcp-macvlan-network:
        ipv4_address: 192.168.12.4
    environment:
      - "ROS_MASTER_URI=http://192.168.12.2:11311"
      - "ROS_HOSTNAME=192.168.12.4"
    ports:
      - "8080:8080"
    privileged: true
    restart: always

  # joy-driver:
  #   image: aictrobotics/mobile-manipulator:latest
  #   container_name: joy-driver
  #   depends_on:
  #     - ros-master
  #   networks:
  #     pcp-macvlan-network:
  #       ipv4_address: 192.168.12.5
  #   command: >
  #     bash -c "source ~/catkin_ws/devel/setup.bash && roslaunch joy dual_joy.launch"
  #   environment:
  #     - "ROS_MASTER_URI=http://192.168.12.2:11311"
  #     - "ROS_HOSTNAME=192.168.12.5"
  #   privileged: true
  #   restart: always


  joy-to-mm:
    image: aictrobotics/mobile-manipulator:latest
    container_name: joy-to-mm
    depends_on:
      - ros-master
    #   - joy-driver
    networks:
      pcp-macvlan-network:
        ipv4_address: 192.168.12.6
    command: >
      bash -c "source ~/catkin_ws/devel/setup.bash && rosrun joy_to_mm joy_to_mm_node.py"
    environment:
      - "ROS_MASTER_URI=http://192.168.12.2:11311"
      - "ROS_HOSTNAME=192.168.12.6"
    privileged: true
    restart: always

  manipulator-driver:
    image: aictrobotics/mobile-manipulator:latest
    container_name: manipulator-driver
    depends_on:
      - ros-master
    networks: 
      pcp-macvlan-network: 
        ipv4_address: 192.168.12.7
    environment:
      - "ROS_MASTER_URI=http://192.168.12.2:11311"
      - "ROS_HOSTNAME=192.168.12.7"
    command: >      
      bash -c "source ~/catkin_ws/devel/setup.bash &&
              roslaunch ur_robot_driver ur3e_bringup.launch robot_ip:=192.168.12.252 controllers:="forward_cartesian_traj_controller joint_group_vel_controller joint_state_controller" stopped_controllers:="pos_joint_traj_controller""
    privileged: true
    restart: always

  mobile-base-driver:
    image: aictrobotics/mobile-manipulator:latest
    container_name: mobile-base-driver
    depends_on:
      - ros-master
    networks:
      pcp-macvlan-network:
        ipv4_address: 192.168.12.8
    environment:
      - "ROS_MASTER_URI=http://192.168.12.2:11311"
      - "ROS_HOSTNAME=192.168.12.8"
      - "DISPLAY=unix$DISPLAY"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "source ~/catkin_ws/devel/setup.bash && roslaunch mir_driver mir.launch"
    privileged: true
    restart: always

  cam-node:
    image: aictrobotics/modee:latest
    container_name: cam-node
    depends_on:
      - ros-master
    networks:
      pcp-macvlan-network:
        ipv4_address: 192.168.12.10
    environment:
      - "ROS_MASTER_URI=http://192.168.12.2:11311"
      - "ROS_HOSTNAME=192.168.12.10"
      - "DISPLAY=unix$DISPLAY"
    # network_mode: "host"
    # ports:
    #   - "192.168.1.9:11311:11311"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >      
      bash -c "source /opt/ros/noetic/setup.bash &&
      rosrun usb_cam usb_cam_node _image_width:=640 _image_height:=480 _pixel_format:="yuyv" _autofocus:=false _focus:=500 _framerate:=30 _autoexposure:=false _exposure:=330 _contrast:=40 _brightness:=0 _saturation:=75 _gain:=128 _sharpness:=50"
    privileged: true
    restart: always

  ocr-node:
    image: aictrobotics/modee:latest
    container_name: ocr-node
    depends_on:
      - ros-master
    networks:
      pcp-macvlan-network:
        ipv4_address: 192.168.12.11
    environment:
      - "ROS_MASTER_URI=http://192.168.12.2:11311"
      - "ROS_HOSTNAME=192.168.12.11"
      - "DISPLAY=unix$DISPLAY" 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      # - ~/github/ocr:/root/catkin_ws/src/ocr
    command: >      
      bash -c "source ~/catkin_ws/devel/setup.bash &&
      roslaunch ocr ocr.launch multiply_value:="1.0" big_ranged_h_low:="0" big_ranged_s_low:="100" big_ranged_v_low:="0" big_ranged_h_high:="50" big_ranged_s_high:="255" big_ranged_v_high:="255"  each_roi_3_x:="55" each_roi_3_y:="190" each_roi_3_w:="40" each_roi_3_h:="40" each_bin_1:="140" each_bin_2:="120" each_bin_3:="120" debug:="False""
    # command: >
    #   bash -c "tail -F anything"
    privileged: true
    restart: always

  # modee-ros-driver:
  #   image: aictrobotics/modee:latest
  #   container_name: modee-ros-driver
  #   depends_on:
  #     - ros-master
  #   networks:
  #     pcp-macvlan-network:
  #       ipv4_address: 192.168.12.12
  #   environment:
  #     - "ROS_MASTER_URI=http://192.168.12.2:11311"
  #     - "ROS_HOSTNAME=192.168.12.12"
  #     - "DISPLAY=unix$DISPLAY" 
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw 
  #     # - ~/github/dynamixel:/root/catkin_ws/src/dynamixel
  #   command: >      
  #     bash -c "source ~/catkin_ws/devel/setup.bash &&
  #     roslaunch dynamixel_workbench_controllers dynamixel_controllers_for_modee.launch"
  #   privileged: true
  #   restart: always

  # 192.168.12.9 is not working (Not sure why)
  mobile-manipulator-driver:
    image: aictrobotics/mobile-manipulator:latest
    container_name: mobile-manipulator-driver
    depends_on:
      - ros-master
      - manipulator-driver
      - mobile-base-driver
    networks:
      pcp-macvlan-network:
        ipv4_address: 192.168.12.12
    environment:
      - "ROS_MASTER_URI=http://192.168.12.2:11311"
      - "ROS_HOSTNAME=192.168.12.12"
      - "DISPLAY=unix$DISPLAY"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "sleep 30 && source ~/catkin_ws/devel/setup.bash && roslaunch mobile_manipulator mobile_manipulator.launch output:="screen""
    privileged: true
    restart: always

  # rviz:
  #   image: aictrobotics/mobile-manipulator:latest
  #   container_name: rviz
  #   # depends_on:
  #   #   - ros-master
  #   networks:
  #     pcp-macvlan-network:
  #       ipv4_address: 192.168.12.11
  #   environment:
  #     - "ROS_MASTER_URI=http://192.168.12.2:11311"
  #     - "ROS_HOSTNAME=192.168.12.11"
  #     - "DISPLAY=unix$DISPLAY"
  #   volumes: 
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #   command: >
  #     bash -c "source ~/catkin_ws/devel/setup.bash && rviz -d ~/catkin_ws/src/mir_robot/mir_navigation/rviz/navigation.rviz"
  #   privileged: true
  #   restart: always

  # mm-dev-container:
  #   image: aictrobotics/mobile-manipulator:latest
  #   container_name: mm-dev-container
  #   # depends_on:
  #   #   - ros-master
  #   networks:
  #     pcp-macvlan-network:
  #       ipv4_address: 192.168.12.100
  #   environment:
  #     - "ROS_MASTER_URI=http://192.168.12.2:11311"
  #     - "ROS_HOSTNAME=192.168.12.100"
  #     - "DISPLAY=unix$DISPLAY"
  #   volumes: 
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #     - /home/aict/github/pcp/mobile-manipulator:/root/catkin_ws/src/mobile-manipulator
  #     - /home/aict/github/pcp/modee:/root/catkin_ws/src/modee
  #     # - /home/aict/github/universal_robot:/root/catkin_ws/src/fmauch_universal_robot
  #   command: >
  #     bash -c "tail -F anything"
  #   privileged: true
  #   restart: always

  # modee-dev-container:
  #   image: aictrobotics/modee:latest
  #   container_name: modee-dev-container
  #   depends_on:
  #     - ros-master
  #   networks:
  #     pcp-macvlan-network:
  #       ipv4_address: 192.168.12.101
  #   environment:
  #     - "ROS_MASTER_URI=http://192.168.12.2:11311"
  #     - "ROS_HOSTNAME=192.168.12.101"
  #     - "DISPLAY=unix$DISPLAY" 
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw 
  #     # - ~/github/dynamixel:/root/catkin_ws/src/dynamixel
  #     - ~/github/modee:/root/catkin_ws/src/modee
  #   # command: >      
  #   #   bash -c "source ~/catkin_ws/devel/setup.bash &&
  #   #   roslaunch dynamixel_workbench_controllers dynamixel_controllers_for_modee.launch"
  #   command: >      
  #     bash -c "tail -F anything"
  #   privileged: true
  #   restart: always    