version: '2.2'

networks:
  pcp-bridge-network:
    external: true

services:
  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.2
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.2"
    restart: always

  rosbridge-suite:
    image: aictrobotics/rosbridge-suite:latest
    container_name: rosbridge-suite
    command: >
      bash -c "roslaunch rosbridge_server rosbridge_websocket.launch"
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.3
    ports:
      - "9090:9090"
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.3"
    restart: always

  simulator:
    image: aictrobotics/turtlebot3:latest
    container_name: simulator
    # depends_on:
    #   - ros-master
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.4
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.4"
      - "DISPLAY=unix$DISPLAY"
      # network_mode: "host"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "source ~/catkin_ws/devel/setup.bash && export TURTLEBOT3_MODEL=waffle_pi && roslaunch turtlebot3_gazebo turtlebot3_world.launch"
    privileged: true
    restart: always

  foxglove:
    image: ghcr.io/foxglove/studio:latest
    container_name: foxglove
    networks:
      pcp-bridge-network:
        ipv4_address: 192.168.56.5
    environment:
      - "ROS_MASTER_URI=http://192.168.56.2:11311"
      - "ROS_HOSTNAME=192.168.56.5"
    ports:
      - "8080:8080"
    privileged: true
    restart: always
