version: '2.2'

# networks:
#   ros:
#     driver: bridge
networks:
  pcp-macvlan-network:
    name: pcp-macvlan-network
    driver: macvlan
    driver_opts:
      parent: enp89s0
    ipam:
      config:
        - subnet: "10.42.0.0/24"
          # ip_range: "192.168.0.64/26"
          gateway: "10.42.0.1"

services:
  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    # networks:
    #   - ros
    # environment:
    #   - "ROS_MASTER_URI=http://ros-master:11311"
    #   - "ROS_HOSTNAME=ros-master"
    network_mode: "host"
    restart: always

  cam-node:
    image: aictrobotics/modee:latest
    container_name: cam-node
    # depends_on:
    #   - ros-master
    networks:
      pcp-macvlan-network:
        ipv4_address: 10.42.0.2
    environment:
      - "ROS_MASTER_URI=http://192.168.1.9:11311"
      - "ROS_HOSTNAME=10.42.0.2"
      - "DISPLAY=unix$DISPLAY"
    # network_mode: "host"
    # ports:
    #   - "192.168.1.9:11311:11311"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >      
      bash -c "source /opt/ros/noetic/setup.bash &&
      rosrun usb_cam usb_cam_node _image_width:=640 _image_height:=480 _pixel_format:="yuyv" _autofocus:=false _focus:=500 _framerate:=30 _autoexposure:=false _exposure:=330 _contrast:=40 _brightness:=0 _saturation:=75 _gain:=128 _sharpness:=50"
    privileged: true
    restart: always

  # ocr-node:
  #   image: ocr:latest
  #   container_name: ocr-node
  #   depends_on:
  #     - ros-master
  #   # networks:
  #   #   - ros
  #   environment:
  #   #   - "ROS_MASTER_URI=http://ros-master:11311"
  #   #   - "ROS_HOSTNAME=ocr-node"
  #     - "DISPLAY=unix$DISPLAY" 
  #   network_mode: "host"
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw 
  #     - ~/github/ocr:/root/catkin_ws/src/ocr
  #   command: >      
  #     bash -c "source ~/catkin_ws/devel/setup.bash &&
  #     rosrun ocr ocr_node.py"
  #   privileged: true
  #   restart: always

  # ocr-doc-container:
  #   image: ocr:latest
  #   container_name: ocr-doc-container
  #   # networks:
  #   #   - ros
  #   environment:
  #     # - "ROS_MASTER_URI=http://ros-master:11311"
  #     # - "ROS_HOSTNAME=ocr-dev-container"
  #     - "DISPLAY=unix$DISPLAY" 
  #   network_mode: "host"
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw 
  #     - ~/github/ocr:/root/catkin_ws/src/ocr
  #   command: >      
  #     bash -c "source ~/catkin_ws/devel/setup.bash
  #     && cd ~/catkin_ws/src/ocr
  #     && rosdoc_lite .
  #     && python3 -m http.server --directory doc/html 9999"
  #   privileged: true
  #   restart: always

  # modee-doc-container:
  #   image: modee:latest
  #   container_name: modee-doc-container
  #   # networks:
  #   #   - ros
  #   environment:
  #     # - "ROS_MASTER_URI=http://ros-master:11311"
  #     # - "ROS_HOSTNAME=ocr-dev-container"
  #     - "DISPLAY=unix$DISPLAY" 
  #   network_mode: "host"
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw 
  #     - ~/github/modee:/root/catkin_ws/src/modee
  #   command: >      
  #     bash -c "source ~/catkin_ws/devel/setup.bash
  #     && cd ~/catkin_ws/src/modee
  #     && rosdoc_lite .
  #     && python3 -m http.server --directory doc/html 9998"
  #   privileged: true
  #   restart: always

  # # modee-ros-driver:
  # #   image: aictrobotics/modee:latest
  # #   container_name: modee-ros-driver
  # #   depends_on:
  # #     - ros-master
  # #   # networks:
  # #   #   - ros
  # #   environment:
  # #   #   - "ROS_MASTER_URI=http://ros-master:11311"
  # #   #   - "ROS_HOSTNAME=ocr-node"
  # #     - "DISPLAY=unix$DISPLAY" 
  # #   network_mode: "host"
  # #   volumes:
  # #     - /tmp/.X11-unix:/tmp/.X11-unix:rw 
  # #     - ~/github/dynamixel:/root/catkin_ws/src/dynamixel
  # #   command: >      
  # #     bash -c "source ~/catkin_ws/devel/setup.bash &&
  # #     roslaunch dynamixel_workbench_controllers dynamixel_controllers_for_modee.launch"
  # #   privileged: true
  # #   restart: always

  # modee-dev-container:
  #   image: modee:latest
  #   container_name: modee-dev-container
  #   # networks:
  #   #   - ros
  #   network_mode: "host"
  #   environment:
  #     # - "ROS_MASTER_URI=http://ros-master:11311"
  #     # - "ROS_HOSTNAME=modee-dev-container"
  #     - "DISPLAY=unix$DISPLAY" 
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw 
  #     - ~/github/modee:/root/catkin_ws/src/modee
  #   command: tail -F anything
  #   privileged: true
  #   restart: always

  # ocr-dev-container:
  #   image: ocr:latest
  #   container_name: ocr-dev-container
  #   # networks:
  #   #   - ros
  #   environment:
  #     # - "ROS_MASTER_URI=http://ros-master:11311"
  #     # - "ROS_HOSTNAME=ocr-dev-container"
  #     - "DISPLAY=unix$DISPLAY" 
  #   network_mode: "host"
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw 
  #     - ~/github/ocr:/root/catkin_ws/src/ocr
  #   command: tail -F anything
  #   privileged: true
  #   restart: always

  # dev-container:
  #   image: aictrobotics/modee:latest
  #   container_name: dev-container
  #   # networks:
  #   #   - ros
  #   environment:
  #     # - "ROS_MASTER_URI=http://ros-master:11311"
  #     # - "ROS_HOSTNAME=dev-container"
  #     - "DISPLAY=unix$DISPLAY" 
  #   # # network_mode: "host"
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw 
  #     - /home/aict/github/pcp/modee:/root/catkin_ws/src/modee
  #   command: tail -F anything
  #   privileged: true
  #   restart: always
